name: Deploy Staging

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:

  deploy-infra-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-central-1"

      - name: Deploy Waf Staging
        id: waf
        uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
        if: github.ref == 'refs/heads/staging'
        with:
          name: finance-waf-staging
          template: templates/waf.yml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: >-
            Environment=staging

      - name: Deploy Frontent Infra Staging
        id: frontend-infra-staging
        uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
        if: github.ref == 'refs/heads/staging'
        with:
          name: finance-frontend-infra-staging
          template: templates/frontend-infra.yml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: >-
            Environment=staging,
            CertificateARN=arn:aws:acm:us-east-1:996819435370:certificate/7719cc99-e95e-4477-87d6-82538f5f87b1,
            BucketName=staging.clearsight.finance
            
      - name: Deploy Backend Infra Staging
        id: backend-infra-staging
        if: github.ref == 'refs/heads/staging'
        uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
        with:
          name: finance-backend-infra-staging
          template: templates/backend-infra.yml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: >-
            Environment=staging

  build-staging:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install Dependencies
      run: |
        npm install
    - name: Build Application
      run: |
        npm run build

    - name: Upload App to S3 Bucket
      uses: jakejarvis/s3-sync-action@master
      if: github.ref == 'refs/heads/staging'
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: "staging.clearsight.pro"
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: "eu-central-1"
        SOURCE_DIR: "build"
        
    - name: Create CloudFront Cache Invalidation
      uses: chetan/invalidate-cloudfront-action@master
      env:
        DISTRIBUTION: "E2GGAM3WIH7YAZ"
        PATHS: "/*"
        AWS_REGION: "eu-central-1"
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
